sudo: required
services:
  - docker

before_install:
  - docker build -t alexyap1205/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true alexyap1205/react-test npm run test -- --coverage

after_success:
  - docker build -t alexyap1205/multi-client ./client
  - docker build -t alexyap1205/multi-nginx ./nginx
  - docker build -t alexyap1205/multi-server ./server
  - docker build -t alexyap1205/multi-worker ./worker
  # Login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push to docker hub
  - docker push alexyap1205/multi-client
  - docker push alexyap1205/multi-nginx
  - docker push alexyap1205/multi-server
  - docker push alexyap1205/multi-worker
